#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-haml-rails
Version  : 0.9.0
Release  : 1
URL      : https://rubygems.org/downloads/haml-rails-0.9.0.gem
Source0  : https://rubygems.org/downloads/haml-rails-0.9.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-actionpack
BuildRequires : rubygem-actionview
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-builder
BuildRequires : rubygem-bundler
BuildRequires : rubygem-erubis
BuildRequires : rubygem-html2haml
BuildRequires : rubygem-i18n
BuildRequires : rubygem-loofah
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-rails
BuildRequires : rubygem-rails-deprecated_sanitizer
BuildRequires : rubygem-rails-dom-testing
BuildRequires : rubygem-rails-html-sanitizer
BuildRequires : rubygem-railties
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-thor
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo

%description
# Haml-rails
Haml-rails provides Haml generators for Rails 4. It also enables Haml as the templating engine for you, so you don't have to screw around in your own application.rb when your Gemfile already clearly indicated what templating engine you have installed. Hurrah.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n haml-rails-0.9.0
gem spec %{SOURCE0} -l --ruby > rubygem-haml-rails.gemspec

%build
gem build rubygem-haml-rails.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
haml-rails-0.9.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/haml-rails-0.9.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ApplicationLayoutGenerator/cdesc-ApplicationLayoutGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ApplicationLayoutGenerator/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ControllerGenerator/cdesc-ControllerGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ControllerGenerator/handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/MailerGenerator/cdesc-MailerGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/MailerGenerator/copy_view_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/MailerGenerator/formats-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ScaffoldGenerator/available_views-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ScaffoldGenerator/cdesc-ScaffoldGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ScaffoldGenerator/copy_form_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ScaffoldGenerator/copy_view_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/ScaffoldGenerator/handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Engine/cdesc-Engine.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/ActionView/DependencyTracker/cdesc-DependencyTracker.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/ActionView/cdesc-ActionView.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/ActiveSupport/Cache/cdesc-Cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/ActiveSupport/cdesc-ActiveSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/CacheDigests/DependencyTracker/cdesc-DependencyTracker.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/CacheDigests/cdesc-CacheDigests.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/Gem/cdesc-Gem.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/SourceAnnotationExtractor/cdesc-SourceAnnotationExtractor.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/Railtie/cdesc-Railtie.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/Haml/cdesc-Haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/controller/templates/page-view_html_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/mailer/templates/page-layout_html_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/mailer/templates/page-layout_text_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/mailer/templates/page-view_html_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/mailer/templates/page-view_text_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/scaffold/templates/page-_form_html_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/scaffold/templates/page-edit_html_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/scaffold/templates/page-index_html_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/scaffold/templates/page-new_html_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/generators/haml/scaffold/templates/page-show_html_haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/haml-rails-0.9.0/ri/lib/tasks/page-erb2haml_rake.ri
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/Appraisals
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/gemfiles/rails_4_0.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/gemfiles/rails_4_1.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/gemfiles/rails_4_2.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/haml-rails.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/controller/controller_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/controller/templates/view.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/mailer/mailer_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/mailer/templates/layout.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/mailer/templates/layout.text.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/mailer/templates/view.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/mailer/templates/view.text.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/scaffold_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/templates/_form.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/templates/edit.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/templates/index.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/templates/new.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/templates/show.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/haml-rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/haml-rails/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/rails/generators/haml/application_layout/application_layout_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/lib/tasks/erb2haml.rake
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/test/fixtures/routes.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/test/lib/generators/haml/controller_generator_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/test/lib/generators/haml/mailer_generator_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/test/lib/generators/haml/scaffold_generator_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/test/lib/generators/haml/testing_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/haml-rails-0.9.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/haml-rails-0.9.0.gemspec
